// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ-I2Bf9Fwm5SD1U3ePzQL_gcxde5TzFA',
    appId: '1:1098500496995:web:8ba033333f0af75e0ce256',
    messagingSenderId: '1098500496995',
    projectId: 'donna-app-124dc',
    authDomain: 'donna-app-124dc.firebaseapp.com',
    storageBucket: 'donna-app-124dc.firebasestorage.app',
    measurementId: 'G-1JNS0CCVN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbXaVkUj1Zo7aULcJSVABvR0NpBqH1ffk',
    appId: '1:1098500496995:android:e495619f7b3412170ce256',
    messagingSenderId: '1098500496995',
    projectId: 'donna-app-124dc',
    storageBucket: 'donna-app-124dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS0TTniXF8GuxqyUJ2qtloKFY3LqOU-nM',
    appId: '1:1098500496995:ios:7748cb57734ce4f60ce256',
    messagingSenderId: '1098500496995',
    projectId: 'donna-app-124dc',
    storageBucket: 'donna-app-124dc.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
